# EXERCISE 1

In [1]:
import os
os.getcwd()

'C:\\Users\\angel'

In [2]:
import numpy as np
from numpy import genfromtxt
emp_dataIT = genfromtxt("DS1_C4_S1_Employee_Data_Challenge.csv",delimiter= ",",skip_header = 1)
#display the columns and rows of the EMP_DATAIT array
#col 1[0]=emp_code(ID)
#col 2[1]=age
 #DISPLAY ARRAY OF IT EMPLOYEE DATA
emp_dataIT

array([[ 1., 22.],
       [ 2., 27.],
       [ 3., 31.],
       [ 4., 29.],
       [ 5., 27.],
       [ 6., 26.],
       [ 7., 27.],
       [ 8., 23.],
       [ 9., 27.],
       [10., 32.],
       [11., 28.],
       [12., 27.],
       [13., 22.],
       [14., 27.],
       [15., 35.],
       [16., 33.],
       [17., 28.],
       [18., 22.],
       [19., 25.],
       [20., 27.],
       [21., 37.],
       [22., 27.],
       [23., 24.],
       [24., 27.],
       [25., 28.],
       [26., 26.],
       [27., 27.],
       [28., 27.],
       [29., 29.],
       [30., 49.],
       [31., 26.],
       [32., 32.],
       [33., 26.],
       [34., 24.],
       [35., 24.],
       [36., 23.],
       [37., 28.],
       [38., 28.],
       [39., 22.],
       [40., 26.],
       [41., 32.],
       [42., 35.],
       [43., 33.],
       [44., 31.],
       [45., 30.],
       [46., 36.],
       [47., 22.],
       [48., 23.],
       [49., 32.],
       [50., 34.]])

In [3]:
#array dimensions
emp_dataIT.shape


(50, 2)

In [4]:
#access emp_code
emp_code=emp_dataIT[:,0]
emp_code

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [5]:
#access age
age = emp_dataIT[:,1]
age

array([22., 27., 31., 29., 27., 26., 27., 23., 27., 32., 28., 27., 22.,
       27., 35., 33., 28., 22., 25., 27., 37., 27., 24., 27., 28., 26.,
       27., 27., 29., 49., 26., 32., 26., 24., 24., 23., 28., 28., 22.,
       26., 32., 35., 33., 31., 30., 36., 22., 23., 32., 34.])

In [6]:
#TASK 1
#Calculate the average age of the employees in the IT firm
avg_age = np.mean(age)
avg_age

28.26

In [7]:
#TASK 2
#Display the employee IDs/codes of those employees who are above 25 years of age. 

#APPLY CONDITION TO THE  AGE COLUMN
above_25_index = np.where(age > 25)
above_25_index
#Display the employee IDs/codes of those employees who are above 25 years of age. 
print("employee_code for employees older than 25")
print(emp_code[above_25_index])



employee_code for employees older than 25
[ 2.  3.  4.  5.  6.  7.  9. 10. 11. 12. 14. 15. 16. 17. 20. 21. 22. 24.
 25. 26. 27. 28. 29. 30. 31. 32. 33. 37. 38. 40. 41. 42. 43. 44. 45. 46.
 49. 50.]


In [8]:
#TASK 2.1
#Find the count of these employees
num_emp_above_25 = age[above_25_index].size
print("There are ",num_emp_above_25,"employees above 25")

There are  38 employees above 25


In [9]:
#TASK 3
#Display the employee IDs/codes of these employees with ages between 30-35
age_group = np.where((age > 29) &( age <36))
print(emp_dataIT[0:,[0,1]][age_group])


[[ 3. 31.]
 [10. 32.]
 [15. 35.]
 [16. 33.]
 [32. 32.]
 [41. 32.]
 [42. 35.]
 [43. 33.]
 [44. 31.]
 [45. 30.]
 [49. 32.]
 [50. 34.]]


In [10]:
#TASK 3.1
#Calculate the total number of employees who are in the age-group of 30—35 years. 
age_group = np.where((age > 29) &( age <36))
#FIND SIZE OF AGE GROUP ARRAY
num_emp_in_agegroup = age[age_group].size
print("There are",num_emp_in_agegroup,"employees between 30 and 35")

There are 12 employees between 30 and 35


# EXERCISE 2

In [11]:
#IMPORTING DATA
import numpy as np
from numpy import genfromtxt

In [12]:
shopping_data = genfromtxt("DS1_C4_S1_Shopping_Data_Challenge.csv",delimiter= ",",skip_header = 1)
shopping_data
#col[0] = customerID
#col[1] = age
#col[2] = annual income
#col[3] = spending score 

array([[  1.,  19.,  15.,  39.],
       [  2.,  21.,  15.,  81.],
       [  3.,  20.,  16.,   6.],
       [  4.,  23.,  16.,  77.],
       [  5.,  31.,  17.,  40.],
       [  6.,  22.,  17.,  76.],
       [  7.,  35.,  18.,   6.],
       [  8.,  23.,  18.,  94.],
       [  9.,  64.,  19.,   3.],
       [ 10.,  30.,  19.,  72.],
       [ 11.,  67.,  19.,  14.],
       [ 12.,  35.,  19.,  99.],
       [ 13.,  58.,  20.,  15.],
       [ 14.,  24.,  20.,  77.],
       [ 15.,  37.,  20.,  13.],
       [ 16.,  22.,  20.,  79.],
       [ 17.,  35.,  21.,  35.],
       [ 18.,  20.,  21.,  66.],
       [ 19.,  52.,  23.,  29.],
       [ 20.,  35.,  23.,  98.],
       [ 21.,  35.,  24.,  35.],
       [ 22.,  25.,  24.,  73.],
       [ 23.,  46.,  25.,   5.],
       [ 24.,  31.,  25.,  73.],
       [ 25.,  54.,  28.,  14.],
       [ 26.,  29.,  28.,  82.],
       [ 27.,  45.,  28.,  32.],
       [ 28.,  35.,  28.,  61.],
       [ 29.,  40.,  29.,  31.],
       [ 30.,  23.,  29.,  87.],
       [ 3

In [13]:
#access customer ID
cus_id=shopping_data[:,0]
cus_id

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.,
       111., 112., 113., 114., 115., 116., 117., 118., 119., 120., 121.,
       122., 123., 124., 125., 126., 127., 128., 129., 130., 131., 132.,
       133., 134., 135., 136., 137., 138., 139., 140., 141., 142., 143.,
       144., 145., 146., 147., 148., 149., 150., 15

In [14]:
#access age
cus_age =shopping_data[:,1]
cus_age

array([19., 21., 20., 23., 31., 22., 35., 23., 64., 30., 67., 35., 58.,
       24., 37., 22., 35., 20., 52., 35., 35., 25., 46., 31., 54., 29.,
       45., 35., 40., 23., 60., 21., 53., 18., 49., 21., 42., 30., 36.,
       20., 65., 24., 48., 31., 49., 24., 50., 27., 29., 31., 49., 33.,
       31., 59., 50., 47., 51., 69., 27., 53., 70., 19., 67., 54., 63.,
       18., 43., 68., 19., 32., 70., 47., 60., 60., 59., 26., 45., 40.,
       23., 49., 57., 38., 67., 46., 21., 48., 55., 22., 34., 50., 68.,
       18., 48., 40., 32., 24., 47., 27., 48., 20., 23., 49., 67., 26.,
       49., 21., 66., 54., 68., 66., 65., 19., 38., 19., 18., 19., 63.,
       49., 51., 50., 27., 38., 40., 39., 23., 31., 43., 40., 59., 38.,
       47., 39., 25., 31., 20., 29., 44., 32., 19., 35., 57., 32., 28.,
       32., 25., 28., 48., 32., 34., 34., 43., 39., 44., 38., 47., 27.,
       37., 30., 34., 30., 56., 29., 19., 31., 50., 36., 42., 33., 36.,
       32., 40., 28., 36., 36., 52., 30., 58., 27., 59., 35., 37

In [15]:
#access annual income
ann_inc = shopping_data[:,2]
ann_inc


array([ 15.,  15.,  16.,  16.,  17.,  17.,  18.,  18.,  19.,  19.,  19.,
        19.,  20.,  20.,  20.,  20.,  21.,  21.,  23.,  23.,  24.,  24.,
        25.,  25.,  28.,  28.,  28.,  28.,  29.,  29.,  30.,  30.,  33.,
        33.,  33.,  33.,  34.,  34.,  37.,  37.,  38.,  38.,  39.,  39.,
        39.,  39.,  40.,  40.,  40.,  40.,  42.,  42.,  43.,  43.,  43.,
        43.,  44.,  44.,  46.,  46.,  46.,  46.,  47.,  47.,  48.,  48.,
        48.,  48.,  48.,  48.,  49.,  49.,  50.,  50.,  54.,  54.,  54.,
        54.,  54.,  54.,  54.,  54.,  54.,  54.,  54.,  54.,  57.,  57.,
        58.,  58.,  59.,  59.,  60.,  60.,  60.,  60.,  60.,  60.,  61.,
        61.,  62.,  62.,  62.,  62.,  62.,  62.,  63.,  63.,  63.,  63.,
        63.,  63.,  64.,  64.,  65.,  65.,  65.,  65.,  67.,  67.,  67.,
        67.,  69.,  69.,  70.,  70.,  71.,  71.,  71.,  71.,  71.,  71.,
        72.,  72.,  73.,  73.,  73.,  73.,  74.,  74.,  75.,  75.,  76.,
        76.,  77.,  77.,  77.,  77.,  78.,  78.,  7

In [16]:
#access spending score
s_score = shopping_data[:,3]
s_score

array([39., 81.,  6., 77., 40., 76.,  6., 94.,  3., 72., 14., 99., 15.,
       77., 13., 79., 35., 66., 29., 98., 35., 73.,  5., 73., 14., 82.,
       32., 61., 31., 87.,  4., 73.,  4., 92., 14., 81., 17., 73., 26.,
       75., 35., 92., 36., 61., 28., 65., 55., 47., 42., 42., 52., 60.,
       54., 60., 45., 41., 50., 46., 51., 46., 56., 55., 52., 59., 51.,
       59., 50., 48., 59., 47., 55., 42., 49., 56., 47., 54., 53., 48.,
       52., 42., 51., 55., 41., 44., 57., 46., 58., 55., 60., 46., 55.,
       41., 49., 40., 42., 52., 47., 50., 42., 49., 41., 48., 59., 55.,
       56., 42., 50., 46., 43., 48., 52., 54., 42., 46., 48., 50., 43.,
       59., 43., 57., 56., 40., 58., 91., 29., 77., 35., 95., 11., 75.,
        9., 75., 34., 71.,  5., 88.,  7., 73., 10., 72.,  5., 93., 40.,
       87., 12., 97., 36., 74., 22., 90., 17., 88., 20., 76., 16., 89.,
        1., 78.,  1., 73., 35., 83.,  5., 93., 26., 75., 20., 95., 27.,
       63., 13., 75., 10., 92., 13., 86., 15., 69., 14., 90., 32

In [17]:
#TASK 1
#Display the details of the customers whose spending score is greater than 80.
above80_s_score = np.where (s_score > 80)
print(shopping_data[:,[0,3]][above80_s_score])

[[  2.  81.]
 [  8.  94.]
 [ 12.  99.]
 [ 20.  98.]
 [ 26.  82.]
 [ 30.  87.]
 [ 34.  92.]
 [ 36.  81.]
 [ 42.  92.]
 [124.  91.]
 [128.  95.]
 [136.  88.]
 [142.  93.]
 [144.  87.]
 [146.  97.]
 [150.  90.]
 [152.  88.]
 [156.  89.]
 [162.  83.]
 [164.  93.]
 [168.  95.]
 [174.  92.]
 [176.  86.]
 [180.  90.]
 [182.  86.]
 [184.  88.]
 [186.  97.]
 [190.  85.]
 [194.  91.]
 [200.  83.]]


In [18]:
#Display the total count of these customers.
num_above80_s_score = s_score[above80_s_score].size
print("There are",num_above80_s_score,"employees with a spending score above 80")

There are 30 employees with a spending score above 80


In [19]:
#TASK 2
#Extract and display the data of the customers who are 20 to 24 years of age.
#NOTE: This data helps analyze age-related expenditures.
cus_age_group = np.where((cus_age >= 20)&(cus_age <25))
print(shopping_data[cus_age_group])


[[  2.  21.  15.  81.]
 [  3.  20.  16.   6.]
 [  4.  23.  16.  77.]
 [  6.  22.  17.  76.]
 [  8.  23.  18.  94.]
 [ 14.  24.  20.  77.]
 [ 16.  22.  20.  79.]
 [ 18.  20.  21.  66.]
 [ 30.  23.  29.  87.]
 [ 32.  21.  30.  73.]
 [ 36.  21.  33.  81.]
 [ 40.  20.  37.  75.]
 [ 42.  24.  38.  92.]
 [ 46.  24.  39.  65.]
 [ 79.  23.  54.  52.]
 [ 85.  21.  54.  57.]
 [ 88.  22.  57.  55.]
 [ 96.  24.  60.  52.]
 [100.  20.  61.  49.]
 [101.  23.  62.  41.]
 [106.  21.  62.  42.]
 [125.  23.  70.  29.]
 [135.  20.  73.   5.]]


In [20]:
#TASK 3
#Display the IDs of the customers with the lowest annual income and the customers with the highest.
lowest_ann_inc = min(ann_inc)
print("Lowest income: ",lowest_ann_inc)
highest_ann_inc =max(ann_inc)
print("Highest income:",highest_ann_inc)


Lowest income:  15.0
Highest income: 137.0


In [21]:
#TASK 3.1
#Display customer IDs who have the lowest salary
lowest_ann_incID = np.where(ann_inc == 15)
print(shopping_data[:,[0,2]][lowest_ann_incID])


[[ 1. 15.]
 [ 2. 15.]]


In [22]:
#TASK 3.2
#Display Customer ID who has the highest salary
highest_ann_incID = np.where(ann_inc == 137)
print(cus_id[highest_ann_incID])
print(shopping_data[:,[0,2]][highest_ann_incID])

[199. 200.]
[[199. 137.]
 [200. 137.]]


In [23]:
#TASK 4
#Display the details of the customers who are:
#CONDITIONS: less than 45 years of age
    #have an annual income greater than $35k 
    #have a spending score greater than 75

chosen_ones = np.where((cus_age < 45)&(ann_inc > 35)&(s_score > 75))
print(shopping_data[chosen_ones])

[[ 42.  24.  38.  92.]
 [124.  39.  69.  91.]
 [126.  31.  70.  77.]
 [128.  40.  71.  95.]
 [136.  29.  73.  88.]
 [142.  32.  75.  93.]
 [144.  32.  76.  87.]
 [146.  28.  77.  97.]
 [150.  34.  78.  90.]
 [152.  39.  78.  88.]
 [154.  38.  78.  76.]
 [156.  27.  78.  89.]
 [158.  30.  78.  78.]
 [162.  29.  79.  83.]
 [164.  31.  81.  93.]
 [168.  33.  86.  95.]
 [174.  36.  87.  92.]
 [176.  30.  88.  86.]
 [180.  35.  93.  90.]
 [182.  32.  97.  86.]
 [184.  29.  98.  88.]
 [186.  30.  99.  97.]
 [190.  36. 103.  85.]
 [194.  38. 113.  91.]
 [196.  35. 120.  79.]
 [200.  30. 137.  83.]]


In [24]:
#TASK 4.1
#How many such customers are there in the given data?
num_chosen_ones = cus_id[chosen_ones].size
print("There are",num_chosen_ones,"employees that meet these qualifications")

There are 26 employees that meet these qualifications


In [25]:
#TASK 5
#During the Christmas season, the company wishes to offer random gift coupons valued between $10 and $50 to all its customers. 
gift_coupon = np.random.randint(10,50,size =(200,1) )
gift_coupon
print(gift_coupon.shape)
print(shopping_data.shape)

(200, 1)
(200, 4)


In [26]:
#Add a new column for the gift coupons in the existing data
shopping_data = np.append(shopping_data,gift_coupon,axis = 1)


In [27]:
#Display the details of the customers after adding the new column
print(shopping_data)

[[  1.  19.  15.  39.  26.]
 [  2.  21.  15.  81.  22.]
 [  3.  20.  16.   6.  31.]
 [  4.  23.  16.  77.  18.]
 [  5.  31.  17.  40.  41.]
 [  6.  22.  17.  76.  15.]
 [  7.  35.  18.   6.  40.]
 [  8.  23.  18.  94.  36.]
 [  9.  64.  19.   3.  43.]
 [ 10.  30.  19.  72.  31.]
 [ 11.  67.  19.  14.  30.]
 [ 12.  35.  19.  99.  29.]
 [ 13.  58.  20.  15.  46.]
 [ 14.  24.  20.  77.  12.]
 [ 15.  37.  20.  13.  49.]
 [ 16.  22.  20.  79.  43.]
 [ 17.  35.  21.  35.  12.]
 [ 18.  20.  21.  66.  40.]
 [ 19.  52.  23.  29.  34.]
 [ 20.  35.  23.  98.  21.]
 [ 21.  35.  24.  35.  32.]
 [ 22.  25.  24.  73.  34.]
 [ 23.  46.  25.   5.  13.]
 [ 24.  31.  25.  73.  34.]
 [ 25.  54.  28.  14.  46.]
 [ 26.  29.  28.  82.  48.]
 [ 27.  45.  28.  32.  15.]
 [ 28.  35.  28.  61.  21.]
 [ 29.  40.  29.  31.  31.]
 [ 30.  23.  29.  87.  17.]
 [ 31.  60.  30.   4.  31.]
 [ 32.  21.  30.  73.  31.]
 [ 33.  53.  33.   4.  12.]
 [ 34.  18.  33.  92.  42.]
 [ 35.  49.  33.  14.  31.]
 [ 36.  21.  33.  81